services:
  
  # React фронтенд
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "80:80"
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=80
      - REACT_APP_API_URL=http://localhost:5050/api
  
  # Flask API сервер
  api:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      - API_HOST=0.0.0.0
      - API_PORT=5050
    command: python server.py
    depends_on:
      - frontend

  # Telegram бот (опционально, можно запускать отдельно)
  bot:
    build: .
    volumes:
      - ./:/app
    environment:
      - API_HOST=api
      - API_PORT=5050
      - BOT_API_URL=http://api:5050/api
    command: python main_mocked.py
    depends_on:
      - api
